# Generated by Django 6.0.1 on 2026-01-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationreview',
            options={'verbose_name': 'Отзыв об организации', 'verbose_name_plural': 'Отзывы об организациях'},
        ),
        migrations.AlterModelOptions(
            name='volunteerreview',
            options={'verbose_name': 'Отзыв о волонтёре', 'verbose_name_plural': 'Отзывы о волонтёрах'},
        ),
        migrations.RemoveField(
            model_name='organizationreview',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='volunteerreview',
            name='comment',
        ),
        migrations.AddField(
            model_name='organizationreview',
            name='negative_comment',
            field=models.TextField(blank=True, verbose_name='Что можно улучшить'),
        ),
        migrations.AddField(
            model_name='organizationreview',
            name='positive_comment',
            field=models.TextField(blank=True, verbose_name='Что понравилось'),
        ),
        migrations.AddField(
            model_name='volunteerreview',
            name='negative_comment',
            field=models.TextField(blank=True, verbose_name='Что можно улучшить'),
        ),
        migrations.AddField(
            model_name='volunteerreview',
            name='positive_comment',
            field=models.TextField(blank=True, verbose_name='Что понравилось'),
        ),
    ]
