# Generated by Django 6.0.1 on 2026-02-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_volunteerreview_unique_together_initiative'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='absence_reason_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='absence_reason_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='absence_reason_document',
            field=models.FileField(blank=True, null=True, upload_to='absence_reasons/'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'На рассмотрении'),
                    ('approved', 'Одобрено'),
                    ('rejected', 'Отклонено'),
                    ('cancelled', 'Отменено волонтёром'),
                ],
                default='pending',
                max_length=20,
            ),
        ),
    ]

