# Generated by Django 6.0.1 on 2026-02-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_volunteerapplication_absence_and_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationreview',
            name='improvement_comment',
            field=models.TextField(blank=True, verbose_name='Что можно улучшить'),
        ),
        migrations.AddField(
            model_name='volunteerreview',
            name='improvement_comment',
            field=models.TextField(blank=True, verbose_name='Что можно улучшить'),
        ),
        migrations.AlterField(
            model_name='organizationreview',
            name='negative_comment',
            field=models.TextField(blank=True, verbose_name='Что не понравилось'),
        ),
        migrations.AlterField(
            model_name='volunteerreview',
            name='negative_comment',
            field=models.TextField(blank=True, verbose_name='Что не понравилось'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('application_created', 'Новая заявка'), ('application_approved', 'Заявка одобрена'), ('application_rejected', 'Заявка отклонена'), ('review_received', 'Новый отзыв')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]

