# Generated by Django 6.0 on 2025-12-21 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_organizationreview_volunteerreview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organizationreview',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='organizationreview',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization'),
        ),
        migrations.AlterField(
            model_name='volunteerreview',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.volunteerprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationreview',
            unique_together={('organization', 'event', 'volunteer')},
        ),
    ]
