# Generated by Django 6.0 on 2025-12-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_organizationreview_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
