# Generated by Django 6.0 on 2026-01-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_organization_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='no_show_marked',
            field=models.BooleanField(default=False),
        ),
    ]
