import { Link, useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { useAuth } from '@/contexts/AuthContext';
import { Menu, X, User } from 'lucide-react';
import { useState } from 'react';
export default function Navbar() {
  const { user, logout } = useAuth();const navigate = useNavigate();const [isMenuOpen, setIsMenuOpen] = useState(false);
  const handleLogout = () => {logout();navigate('/');};
  return (<nav className="sticky top-0 z-50 w-full border-b bg-white shadow-sm"><div className="container mx-auto px-4 py-3"><div className="flex items-center justify-between"><div className="flex items-center gap-8"><Link to="/" className="flex items-center gap-2"><div className="w-8 h-8 bg-blue-600 rounded-full"></div><span className="text-xl font-bold">Go2Help</span></Link><div className="hidden md:flex items-center gap-6"><Link to="/events" className="text-sm font-medium hover:text-blue-600">Мероприятия</Link><Link to="/organizations" className="text-sm font-medium hover:text-blue-600">Организации</Link><Link to="/volunteers" className="text-sm font-medium hover:text-blue-600">Волонтёры</Link><Link to="/map" className="text-sm font-medium hover:text-blue-600">Карта</Link></div></div><div className="flex items-center gap-4">{user ? (<div className="flex items-center gap-4"><Button variant="outline" asChild><Link to={`/profile/${user.id}`}><User className="w-4 h-4 mr-2" />Профиль</Link></Button><Button variant="outline" onClick={handleLogout}>Выход</Button></div>) : (<div className="flex items-center gap-2"><Button variant="outline" asChild><Link to="/login">Вход</Link></Button><Button asChild><Link to="/register">Регистрация</Link></Button></div>)}<button className="md:hidden" onClick={() => setIsMenuOpen(!isMenuOpen)}>{isMenuOpen ? <X /> : <Menu />}</button></div></div>{isMenuOpen && (<div className="md:hidden mt-4 pb-4 border-t pt-4"><div className="flex flex-col gap-3"><Link to="/events" className="py-2 hover:text-blue-600">Мероприятия</Link><Link to="/organizations" className="py-2 hover:text-blue-600">Организации</Link><Link to="/volunteers" className="py-2 hover:text-blue-600">Волонтёры</Link><Link to="/map" className="py-2 hover:text-blue-600">Карта</Link></div></div>)}</div></nav>);
}
