# Generated by Django 5.2.7 on 2025-12-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='school',
        ),
        migrations.DeleteModel(
            name='Ed_org',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
